// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
var services = [
  {
    title: "Derecho de Familia",
    description: "Divorcios, tenencia, alimentos, adopci\xF3n y todo lo relacionado con el \xE1mbito familiar."
  },
  {
    title: "Derecho Civil",
    description: "Contratos, sucesiones, da\xF1os y perjuicios, y asesoramiento en cuestiones civiles."
  },
  {
    title: "Derecho Laboral",
    description: "Defensa de derechos laborales, despidos, accidentes de trabajo e indemnizaciones."
  },
  {
    title: "Derecho Inmobiliario",
    description: "Compraventa de inmuebles, locaciones, escrituras y regularizaci\xF3n de propiedades."
  },
  {
    title: "Mediaci\xF3n",
    description: "Resoluci\xF3n alternativa de conflictos con enfoque conciliador y resultados efectivos."
  },
  {
    title: "Defensa Penal",
    description: "Asistencia y representaci\xF3n legal en procesos penales con total confidencialidad."
  }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List legal services",
  description: "List the areas of law and legal services offered by the firm, with a short description of each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: services.map((s) => `- ${s.title}: ${s.description}`).join("\n")
      }
    ],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var contact = {
  phone: "2964 61-8615",
  whatsapp: "2964 61-8615",
  email: "contacto@estudiojuridico.com",
  address: "Per\xFA 85, R\xEDo Grande, Tierra del Fuego, Argentina",
  officeHours: "Lunes a Viernes, 15:00 a 19:00 hs"
};
var get_contact_info_default = defineTool2({
  name: "get_contact_info",
  title: "Get contact information",
  description: "Get the law firm's public contact details: phone, WhatsApp, email, office address and opening hours.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          `Tel\xE9fono: ${contact.phone}`,
          `WhatsApp: ${contact.whatsapp}`,
          `Email: ${contact.email}`,
          `Direcci\xF3n: ${contact.address}`,
          `Horario: ${contact.officeHours}`
        ].join("\n")
      }
    ],
    structuredContent: contact
  })
});

// src/lib/mcp/tools/get-firm-overview.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var overview = {
  name: "Estudio Jur\xEDdico",
  tagline: "Defensa Legal con Excelencia",
  summary: "Abogada matriculada con vocaci\xF3n de servicio y compromiso con la justicia. Brinda asesoramiento legal personalizado en diversas ramas del derecho, en R\xEDo Grande, Tierra del Fuego.",
  values: [
    {
      title: "\xC9tica Profesional",
      description: "Cada caso se aborda con integridad, transparencia y un profundo respeto por los valores que rigen la profesi\xF3n."
    },
    {
      title: "Formaci\xF3n Continua",
      description: "Actualizaci\xF3n permanente en las \xFAltimas reformas legislativas y jurisprudencia para brindar el mejor servicio."
    },
    {
      title: "Compromiso Total",
      description: "Dedicaci\xF3n completa a cada cliente, buscando siempre la soluci\xF3n m\xE1s favorable y eficiente para cada situaci\xF3n."
    }
  ]
};
var get_firm_overview_default = defineTool3({
  name: "get_firm_overview",
  title: "Get firm overview",
  description: "Get a public overview of the law firm: who it is, what it stands for, and its core professional values.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          `${overview.name} \u2014 ${overview.tagline}`,
          "",
          overview.summary,
          "",
          ...overview.values.map((v) => `- ${v.title}: ${v.description}`)
        ].join("\n")
      }
    ],
    structuredContent: overview
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "your-custom-page",
  title: "Your Custom Page",
  version: "0.1.0",
  instructions: "Public tools for a law firm website in R\xEDo Grande, Tierra del Fuego (Argentina). Use `get_firm_overview` for who the firm is, `list_services` for the practice areas offered, and `get_contact_info` for phone, WhatsApp, email, address and office hours.",
  tools: [get_firm_overview_default, list_services_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
